vich_uploader:
    db_driver: orm

    mappings:
        project_documents:
            uri_prefix:         /documentos/upload
            upload_destination: %kernel.root_dir%/../web/documentos/upload