<?php

namespace AppBundle\Repository;

/**
 * MensajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensajeRepository extends \Doctrine\ORM\EntityRepository
{
}
