<?php

namespace AppBundle\Repository;

/**
 * PlanificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
