services:
    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }

    appbundle.calendar_listener:
            class: AppBundle\EventListener\CalendarEventListener
            tags:
                - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }
            arguments: ['@doctrine.orm.entity_manager']
